### ISSUE TITLE
Crash with Custom Fonts

### ISSUE THREAD

**Issue by franciscoamado** [skyweb07/Snap.swift#16]
Hey there!

I've been trying to use this framework and stumbled across this issue.
It appears that Custom Fonts don't load on Unit Tests.

Do you know any workaround this? Or will you think on supporting it somehow?

Thanks 👍🏻

**Comment by skyweb07** [comment]
Hey @FranciscoAmado, thanks for reporting the issue, do you have any test project so I can debug it?

**Comment by franciscoamado** [comment]
Hey there!
So, I've been trying to reproduce the error on a smaller project but it seems to work fine -.-
It takes the snapshot well and the test also passes next...
You can consider this closed. I have to go deeper on the other project to try and understand why I'm not getting it right xD
The main difference from this smaller project is that the other project is a single framework instead of an App.. maybe that's the problem. (The Unit Tests run with no Host Application, thus probably no Bundle Resources)

If you wanna take a look: https://github.com/FranciscoAmado/CustomFontTest-ios

Also, thanks for building Snap.swift, its great 👍

**Comment by skyweb07** [comment]
ohh that's nice to hear, about the `framework` problem I think it's random, I'm using for another project and fonts seems to load correctly as they are bundled with the main app so it's weird. If you found the issue just comment back, thanks for reporting this 👍
