### ISSUE TITLE
Project file paths with spaces don't work

### ISSUE THREAD

**Issue by rnystrom** [skyweb07/Snap.swift#22]
[This line](https://github.com/skyweb07/Snap.swift/blob/develop/Snap/Core/Domain/Model/TestTarget+Reference.swift#L39) returns `nil` when the project path has a space in it. I tried hacking around this, but am getting blocked at the moment. I'm going to update my project paths for the time being, but wanted to flag that this took me a minute to debug.

**Comment by skyweb07** [comment]
Hey @rnystrom thanks for finding this issue, I've already pushed a fix https://github.com/skyweb07/Snap.swift/pull/23 for it, could you take a look and tell me if works for you, thank you!!

**Comment by rnystrom** [comment]
Patched this branch via

```
pod 'Snap.swift', :git => 'https://github.com/skyweb07/Snap.swift.git', :branch => 'feature/fix_image_generation_for_directory_with_spaces
```

And tests pass! Thanks @skyweb07!

**Comment by skyweb07** [comment]
Great @rnystrom, I'm adding some test to cover those problems, will release a version later today, thanks for the feedback 🖖🏽
