### ISSUE TITLE
Integrate kaleidoscope

### ISSUE THREAD

**Issue by PhilippeRiegert** [skyweb07/Snap.swift#27]
Hi, thanks so much for this library!

I recently migrate from FBSnapshotTestCase and I was wondering if it would be possible to integrate [Kaleidoscope](https://www.kaleidoscopeapp.com)?
It was very useful in FBSnapshotTestCase when it fail to compare easily with Kaleidoscope with the 
[ksdiff](https://www.kaleidoscopeapp.com/ksdiff2) command line directly in the console.

Thanks !

**Comment by skyweb07** [comment]
Hey @PhilippeRiegert, thanks for the suggestions, it's a good idea to integrate with that tool but you could also take advantage of the Snap built-in tool using the attachments API from Xcode that let you see the same as Kaleidoscope

<img width="1102" alt="method_1" src="https://user-images.githubusercontent.com/747750/34461658-48c7354e-ee30-11e7-8205-81d784c9da10.png">

It will generate a report with the failed image/ the diffed one and the original in case of failure on the test, it's pretty handy for this situations. I'll also take a look at Kaleidos to see if it's easy to integrate.

Thanks and happy new year 🎉

**Comment by PhilippeRiegert** [comment]
Thanks ! 🎉
