### ISSUE TITLE
Make size property of Device type public

### ISSUE THREAD

**Issue by Jeehut** [skyweb07/Snap.swift#36]
In one of my tests I need to see what a view would look like on different devices, but the view is going to be part of a scrollview and therefore is potentially longer than the screen is long. I'd like to test that my view looks correct for each width of a device, but there's no way currently to do that.

The easiest way to allow this is to make the Device sizes public.

**Comment by skyweb07** [comment]
Great!!, I also was thinking about putting a custom one so you can pass custom devices sizes and be more configurable.
