### ISSUE TITLE
Debugging failure on Travis CI

### ISSUE THREAD

**Issue by rnystrom** [skyweb07/Snap.swift#50]
I have a consistent [failure](https://travis-ci.org/GitHawkApp/StyledTextKit/builds/404011006?utm_source=github_status&utm_medium=notification) for githawkapp/StyledTextKit#44 only on Travis CI that I'm struggling to debug. Everything is green locally, but just a single test repeatedly fails on Travis.

If I run the same `xcodebuild` command locally, everything passes. Same goes for testing within Xcode.

Any tips?

**Comment by skyweb07** [comment]
sorry, I've been a little off, checking at the issue it seems to be related with the device you're testing, are you testing with the same device on ci and on local? remember that snap it's not device agnostic yet

**Comment by rnystrom** [comment]
@skyweb07 It's only for a single test which repeatedly fails.

```
Test Case '-[Tests.SnapTests test_complexBuilder]' started.
/Users/travis/build/GitHawkApp/StyledTextKit/Pods/Snap.swift/Snap/Core/Application/Actions/CompareImages.swift:52: error: -[Tests.SnapTests test_complexBuilder] : failed - ≠ Images are not equal
Test Case '-[Tests.SnapTests test_complexBuilder]' failed (0.098 seconds).
```

Really struggling on how to even debug this w/ Travis.

Going to try updating Travis to Xcode 10 and regenerate assets...

**Comment by rnystrom** [comment]
Fixed!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
