### ISSUE TITLE
Write failing test images to file.

### ISSUE THREAD

**Issue by niilohlin** [skyweb07/Snap.swift#9]
Or at least output the offending test image somewhere.

**Comment by skyweb07** [comment]
Hey @niilohlin, actually the library is showing the diff image and the errored one, you can see it in the Xcode report 

<img width="400" alt="screen shot 2017-11-28 at 21 39 24" src="https://user-images.githubusercontent.com/747750/33343186-bea09b40-d484-11e7-8fed-0231a781752e.png">

I avoided the writing to the file cause it's not a necessary file if you have Xcode, do you need the output file in any case?

thanks!

**Comment by niilohlin** [comment]
I intended to use the offending file in our CI environment.

**Comment by skyweb07** [comment]
mmm yeah, for CI make sense, I'll add that image to the output files then
